# Simple workflow for deploying static content to GitHub Pages
name: Sitemap Update Automation

on:
  # Runs on pushes targeting the staging branch
  push:
    branches: ["staging"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pull-requests: write

# Allow one concurrent deployment
concurrency:
  group: "sitemap"
  cancel-in-progress: true

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Sitemap Generation
    steps:
    
    #enable ssh signing for github actions
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    
    - name: Sitemap Generation
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://shihlings.github.io/explore-microcontroller/
        sitemap-format: xml
    
    - name: Output Generation Status
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
    
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4.2.3
      with:
        title: "Automated sitemap update"
        body: > 
          Automated changes. Sitemap updated by 
          the [generate-sitemap](https://github.com/cicirello/generate-sitemap) 
          GitHub action.  
        commit-message: "Automated sitemap update."
        author: Shih-Ling Shen <114762019+shihlings@users.noreply.github.com>
        committer: Shih-Ling Shen <114762019+shihlings@users.noreply.github.com>
        branch: sitemap-update
        delete-branch: true
    
    - name: Approve Pull Request
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        gh pr merge sitemap-update --merge
      env:
        GH_TOKEN: ${{ secrets.TOKEN_PR_APPROVAL }}
